name = "Arthurs Modpack 1.18"
author = "Arthurmeade12"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d92b190bcb78599f0af7466064773586324bcfc5ecd709b65e742a70afed4954"

[versions]
minecraft = "1.18"
quilt = "0.18.10"
